# Generated by Django 4.2.13 on 2024-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Touristplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Weather', models.CharField(max_length=200)),
                ('Location_State', models.CharField(max_length=200)),
                ('Location_District', models.CharField(max_length=200)),
                ('Images', models.ImageField(upload_to='tour/')),
                ('Description', models.CharField(max_length=300)),
            ],
        ),
    ]
